# don't change
config-version: 1

config:
  
  #en/es/cn
  lang: cn

  integrations:
    WorldGuard: false
    MythicMobs: false
    PlaceholderAPI: true
    mcMMO: false
    MMOCore: false
    AureliumSkills: false

  #季节特性
  season:
    #是否启用
    enable: false
    #需要解析的季节变量
    papi: '%customcrops_season%'

  #假如某个地方不存在特殊鱼，是否能让玩家获得原版的钓鱼战利品
  #如果设置为false，那么玩家无法在不满足条件的地方钓起任何物品
  #你也可以根据原版钓鱼战利品写入本插件内以接近原版
  vanilla-loot-when-no-custom-fish: false

  #只有在开放水域才能钓到特殊鱼
  need-open-water: true

  #是否只有本插件的鱼竿能钓到鱼
  need-special-rod: false

  #使用找鱼器的冷却时间(ms)
  fishfinder-cooldown: 3000

  #修改捕鱼所需的时间
  #在paper.yml中可以修改默认最少最长上钩时间
  time-multiply: 2

  #是否启用钓鱼比赛(修改此项需要重启)
  fishing-competition: true

  #转换MMOItems鱼竿为插件物品鱼竿(修改此项需要重启)
  convert-MMOITEMS: false

  # ProtocolLib 模式 (修改此项需要重启)
  protocollib-bossbar: false