# don't change
config-version: '3'

config:
  #en/es/cn
  lang: en

  integrations:
    # fishing region hook
    WorldGuard: false

    # mobs hook
    MythicMobs: false

    # Papi hook
    PlaceholderAPI: true

    # Skill xp hook
    mcMMO: false
    MMOCore: false
    AureliumSkills: false
    EcoSkills: false

    # Season hook
    CustomCrops: false
    RealisticSeasons: false

  season:
    # Season Papi
    # If you enabled CustomCrops or RealisticSeasons season hook, this option will not take effect
    enable: false
    papi: '%customcrops_season%'

  # The same to vanilla
  need-open-water: true

  # Players must use rods with CustomFishing's NBT Tags
  need-special-rod: false

  # does rod lose durability when player successfully fish
  rod-lose-durability: true

  # If there's no custom fish in this place or players don't have a special rod
  # Should players get loots in vanilla way?
  # This should be compatible with other fishing plugin's loot system
  vanilla-loot-when-no-custom-fish: true

  # Cool down time of fish finder
  fishfinder-cooldown: 3000

  # Change the time bobber needs to be hooked
  time-multiply: 2

  # Enable Competition(Requires a restart)
  fishing-competition: true

  # Convert MMOItems' rod into CustomFishing's rod (Requires a restart)
  convert-MMOITEMS: true