# don't change
config-version: 1

config:
  #en/es/cn
  lang: en

  integrations:
    WorldGuard: false
    MythicMobs: false
    PlaceholderAPI: true
    mcMMO: false
    MMOCore: false
    AureliumSkills: false

  season:
    enable: false
    # Season Papi
    papi: '%customcrops_season%'

  # If there's no custom fish in this place
  # Should players get vanilla loots?
  vanilla-loot-when-no-custom-fish: false

  # The same to vanilla
  need-open-water: true

  # Players must use rods with CustomFishing's NBT Tags
  need-special-rod: false

  # Cool down time of fish finder
  fishfinder-cooldown: 3000

  # Change the time bobber needs to be hooked
  time-multiply: 2

  # Enable Competition(Requires a restart)
  fishing-competition: true

  # Convert MMOItems' rod into CustomFishing's rod (Requires a restart)
  convert-MMOITEMS: true