name: CustomFishing
version: '${version}'
main: net.momirealms.customfishing.CustomFishing
api-version: 1.16
authors: [ XiaoMoMi ]
softdepend:
  - MythicMobs
  - PlaceholderAPI
  - WorldGuard
  - mcMMO
  - AureliumSkills
  - MMOCore
commands:
  customfishing:
    usage: /customfishing
    description: main command
    permission: customfishing.admin